### ISSUE TITLE
sparse_categorical_crossentropy vs categorical_crossentropy Loss Function

### ISSUE THREAD

**Issue by AmbiTyga** [filipefborba/HandRecognition#2]
Why did you used sparse_categorical_crossentropy?
I don't find true labels one-hot encoded while processing the datasets.
Please elaborate why did you used sparse_categorical_crossentropy instead of categorical_crossentropy.

**Comment by filipefborba** [comment]
If I remember correctly, sparse_categorical_crossentropy is used for non-one-hot-encoded datasets. Also, the classes are mutually exclusive, so we don't need probabilities...

**Comment by atomar2000** [comment]
yes, thats right....in this the labels are mutually exclusive and there is no need to find a multi-hot vector.....we just need to find a one-hot vector, that is, only one label as the output.....
therefore, categorical_crossentropy should've been used in my opinion.
